server:
    #服务端口
    port: 8761
eureka:
    client:
        #是否要注册它自己(本身就是一个微服务)
        register-with-eureka: false
        #是否同步其它注册中心的信息
        fetch-registry: false
        service-url:
            #访问注册中心的地址
          defaultZone: http://localhost:8761/eureka/
#spring:
#    application:
#        name: eureka-server
#    cloud:
#        config:
#            label: master
#            profile: dev
#            uri: http://localhost:8888
#            discovery:
#                enabled: true
#                service-id: config-server
##mybatis
#mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.springcloud.config.entity
